spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./delivery_app
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#         show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate:
      SQL: debug
      type:
        descriptor:
          sql: trace
#   org.hibernate.type: trace

jwt:
  secret.key: kimminseong_deliverty-application-2023.secret_key
  token.expired-time-ms: 2592000000
  jwt:
    expired-time-ms:


redis:
  host: 192.168.0.26
  port: 6379

server.port: 8081